### ISSUE TITLE
Privacy scope picker

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#128]
Component for picking a privacy scope

Inputs: The possible values for the fields that define a [privacy scope](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#privacy-scope) (i.e. Data category, processing category, purposes of processing)

**Comment by jboileau99** [comment]
@noelmace I plan to include this component and others to come in the @blindnet/core package. I think this component is one which could be useful for developers building their own PRCI, so we should export it individually so they can do:
```typescript
import '@blindnet/core/privacy-scope-picker'
```

**Comment by noelmace** [comment]
@jboileau99 remember the `@blindnet/core` package will be required by **all** Privacy Components for the Web, including the one which won't provide a web component and therefore doesn't use lit. Adding such components to the `@blindnet/core` library could therefore severely damage loading performance for all packages. Especially as tree shaking isn't available for all builds.

IMHO, it would be preferable to either:

1. keep this component in a separate package and use it as a dependency in the PRCI
2. OR, if you really believe such web components are certain to be used by all other web components packages, initiate a "component library": a package providing (i.e. exporting) several user-facing components instead of one.
