### ISSUE TITLE
PRCI - Non-mock API

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#31]
Will use auth token in header eventually

Sample request:

```curl
curl --location --request POST 'https://devkit-pce-staging.azurewebsites.net/v0/privacy-request' \
--header 'Content-Type: application/json' \
--data-raw '{
    "demands": [
        {
            "id": "0",
            "action": "TRANSPARENCY"
        },
        {
            "id": "1",
            "action": "TRANSPARENCY.DATA-CATEGORIES"
        },
        {
            "id": "2",
            "action": "TRANSPARENCY.DPO"
        },
        {
            "id": "3",
            "action": "TRANSPARENCY.KNOWN"
        },
        {
            "id": "4",
            "action": "TRANSPARENCY.LEGAL-BASES"
        },
        {
            "id": "5",
            "action": "TRANSPARENCY.ORGANIZATION"
        },
        {
            "id": "6",
            "action": "TRANSPARENCY.POLICY"
        },
        {
            "id": "7",
            "action": "TRANSPARENCY.PROCESSING-CATEGORIES"
        },
        {
            "id": "8",
            "action": "TRANSPARENCY.PROVENANCE"
        },
        {
            "id": "9",
            "action": "TRANSPARENCY.PURPOSE"
        },
        {
            "id": "10",
            "action": "TRANSPARENCY.RETENTION"
        },
        {
            "id": "11",
            "action": "TRANSPARENCY.WHERE"
        },
        {
            "id": "12",
            "action": "TRANSPARENCY.WHO"
        }
    ],
    "data_subject": [
        {
            "id": "4f04dbb4-d77d-49df-ae57-52aae9d6f3b5",
            "schema": "dsid"
        }
    ]
}'
```

Response:
[Untitled.txt](https://github.com/blindnet-io/privacy-components-web/files/9198060/Untitled.txt)

**Comment by milstan** [comment]
@jboileau99 @m4rk055 there are some issues in the json file of the response:
- `demands` is not a property of the Privacy Repsonse. Instead the reponses to particular demands are nested withing the global response using the `includes` property. I.e. instead of `demands` you need `includes`
- there is no need to (although not an error either include "message": null, "includes": null, "data": null. Those properties are optional can just be omitted
- "lang": "en" makes sense only when there is a non null message. Otherwise the terms themselves are language independant and can be presented to the user in different languages (when localisation of Terms descriptions are awailable)
- `duration` is not a number ("duration": "10") but a [JSON duration](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3.1) see [here](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3.1)
- I've [initially planned system IDs to be URIs (not "system": "sys1")](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#addressability-of-system-endpoints). I am ready to challenge this if there are arguments in favor of something else.
- `answer` can't be booelan ( "answer": false ). I[ has to be one of the PRIV terms.](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#privacy-request-response) . PRIV has "YES" and "NO" terms for this. Either we allow boolean among values of `answer` of we stop using it and use PRIV Terms instead. The advantage of PRIV terms YES/NO is that when a system implements PRIV, and they want to localise user-facing descriptions of answers, they only have to provide translations of PRIV terms, and having `YES` and `NO` makes it difficult to forget to translate them - they just have to provide translations for every PRIV term description including this one.
- Also I realise that `answers` can (in addition to PRVI terms) be PRIV objects (Retention Policies, and Legal Bases). This is not defined in PRIV, and the usage you make here is appropriate. So I will update PRIV to allow this.

**Comment by jboileau99** [comment]
@milstan How you've described it is pretty close to how I have the privacy-response [type](https://github.com/blindnet-io/privacy-components-web/blob/main/src/models/privacy-response.ts) on `main` currently. I've modified it on the [`real-api`](https://github.com/blindnet-io/privacy-components-web/blob/real-api/src/models/privacy-response.ts) branch just so we can use the actual API for now, but @m4rk055 just let me know whenever it changes and I'll update the type again.

**Comment by m4rk055** [comment]
> demands is not a property of the Privacy Repsonse. Instead the reponses to particular demands are nested withing the global response using the includes property. I.e. instead of demands you need includes

I don't think we need a global response object since the system is responding to particular demands. There needs to be only the wrapper object for privacy responses (for demands). (many fields in the [Privacy Response object](https://github.com/blindnet-io/privacy-components-web/blob/main/src/models/privacy-response.ts) do not make sense "globally").

> there is no need to (although not an error either include "message": null, "includes": null, "data": null. Those properties are optional can just be omitted

In the REST API, it's the same thing for a field to have the null value or not exist at all. It just depends on how the particular server encodes it.

> duration is not a number ("duration": "10") but a [JSON duration](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3.1) see [here](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3.1)

I left it for later. We need to create/find encoder for the JSON duration format.

> I've [initially planned system IDs to be URIs (not "system": "sys1")](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#addressability-of-system-endpoints). I am ready to challenge this if there are arguments in favor of something else.

We should create a new optional field then, since it has a specific purpose (web3 and auth).
The current field `system` can contain any unique identifier, e.g. uuid.

> "lang": "en" makes sense only when there is a non null message. Otherwise the terms themselves are language independant and can be presented to the user in different languages (when localisation of Terms descriptions are awailable)
>
> answer can't be booelan ( "answer": false )

Let's update that @jboileau99

**Comment by jboileau99** [comment]
> > "lang": "en" makes sense only when there is a non null message. Otherwise the terms themselves are language independant and can be presented to the user in different languages (when localisation of Terms descriptions are awailable)
> > answer can't be booelan ( "answer": false )
> 
> Let's update that @jboileau99

Will this change on the api side before the v0.3 release?

**Comment by milstan** [comment]
> demands is not a property of the Privacy Repsonse. Instead the reponses to particular demands are nested withing the global response using the includes property. I.e. instead of demands you need includes
> 
> I don't think we need a global response object since the system is responding to particular demands. There needs to be only the wrapper object for privacy responses (for demands). (many fields in the [Privacy Response object](https://github.com/blindnet-io/privacy-components-web/blob/main/src/models/privacy-response.ts) do not make sense "globally").

TBH I don't understand what you mean here. 

The Privacy Response in PRIV is designed to work in many different situations (including coordinated response scenario, where one systems gathers responses from other systems and joins them). If you think some of the desing should be change, let's see what and why

**Comment by milstan** [comment]
> I've [initially planned system IDs to be URIs (not "system": "sys1")](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#addressability-of-system-endpoints). I am ready to challenge this if there are arguments in favor of something else.
> 
> We should create a new optional field then, since it has a specific purpose (web3 and auth).
> The current field system can contain any unique identifier, e.g. uuid.

Or we can specify in PRIV that is not the URL but UUID.

**Comment by m4rk055** [comment]
@jboileau99 Change should be live now.

@milstan I'll think about the response model and discuss it tomorrow. Since there is a coordinated scenario, what I proposed is not complete.
